apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: eirini
build:
  local:
    concurrency: 4
  artifacts:
  - image: eirini/opi
    custom:
      buildCommand: ./scripts/build opi
      dependencies:
        command: ./scripts/deps opi
  - image: eirini/route-collector
    custom:
      buildCommand: ./scripts/build route-collector
      dependencies:
        command: ./scripts/deps route-collector
  - image: eirini/eirini-controller
    custom:
      buildCommand: ./scripts/build eirini-controller
      dependencies:
        command: ./scripts/deps eirini-controller
  - image: eirini/event-reporter
    custom:
      buildCommand: ./scripts/build event-reporter
      dependencies:
        command: ./scripts/deps event-reporter
  - image: eirini/instance-index-env-injector
    custom:
      buildCommand: ./scripts/build instance-index-env-injector
      dependencies:
        command: ./scripts/deps instance-index-env-injector
  - image: eirini/metrics-collector
    custom:
      buildCommand: ./scripts/build metrics-collector
      dependencies:
        command: ./scripts/deps metrics-collector
  - image: eirini/route-pod-informer
    custom:
      buildCommand: ./scripts/build route-pod-informer
      dependencies:
        command: ./scripts/deps route-pod-informer
  - image: eirini/route-statefulset-informer
    custom:
      buildCommand: ./scripts/build route-statefulset-informer
      dependencies:
        command: ./scripts/deps route-statefulset-informer
  - image: eirini/task-reporter
    custom:
      buildCommand: ./scripts/build task-reporter
      dependencies:
        command: ./scripts/deps task-reporter
deploy:
  kubectl:
    manifests:
    - ../eirini-release/scripts/assets/wiremock.yml
  helm:
    releases:
    - name: nats
      remote: true
      chartPath: bitnami/nats
      namespace: eirini-core
      setValueTemplates:
        auth.user: nats
        auth.password: "{{.NATS_PASSWORD}}"
    - name: eirini
      chartPath: ../eirini-release/helm
      namespace: eirini-core
      valuesFiles:
      - ../eirini-release/scripts/assets/value-overrides.yml
      artifactOverrides:
        images.api: eirini/opi
        images.route_collector: eirini/route-collector
        images.eirini_controller: eirini/eirini-controller
        images.event_reporter: eirini/event-reporter
        images.metrics_collector: eirini/metrics-collector
        images.route_statefulset_informer: eirini/route-statefulset-informer
        images.route_pod_informer: eirini/route-pod-informer
        images.task_reporter: eirini/task-reporter
        images.instance_index_env_injector: eirini/instance-index-env-injector
