apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: eirini
build:
  local:
    concurrency: 4
  artifacts:
  - image: eirini/api
    custom:
      buildCommand: ./scripts/build api
      dependencies:
        command: ./scripts/deps api
  - image: eirini/eirini-controller
    custom:
      buildCommand: ./scripts/build eirini-controller
      dependencies:
        command: ./scripts/deps eirini-controller
  - image: eirini/event-reporter
    custom:
      buildCommand: ./scripts/build event-reporter
      dependencies:
        command: ./scripts/deps event-reporter
  - image: eirini/instance-index-env-injector
    custom:
      buildCommand: ./scripts/build instance-index-env-injector
      dependencies:
        command: ./scripts/deps instance-index-env-injector
  - image: eirini/task-reporter
    custom:
      buildCommand: ./scripts/build task-reporter
      dependencies:
        command: ./scripts/deps task-reporter
  - image: eirini/migration
    custom:
      buildCommand: ./scripts/build migration
      dependencies:
        command: ./scripts/deps migration
deploy:
  kubectl:
    manifests:
    - ../eirini-release/scripts/assets/wiremock.yml
  helm:
    releases:
    - name: prometheus
      remote: true
      chartPath: prometheus-community/prometheus
      namespace: eirini-core
    - name: eirini
      chartPath: ../eirini-release/helm
      namespace: eirini-core
      valuesFiles:
      - ../eirini-release/scripts/assets/value-overrides.yml
      setValueTemplates:
        webhook_ca_bundle: "{{.CA_BUNDLE}}"
        resource_validator_ca_bundle: "{{.CA_BUNDLE}}"
      artifactOverrides:
        images.api: eirini/api
        images.eirini_controller: eirini/eirini-controller
        images.event_reporter: eirini/event-reporter
        images.task_reporter: eirini/task-reporter
        images.instance_index_env_injector: eirini/instance-index-env-injector
        images.migration: eirini/migration
